package uy.edu.ude.sipro.ui.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import uy.edu.ude.sipro.ui.componentes.Order;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BusquedaViewDesign extends VerticalLayout {
	protected Panel searchPanel;
	protected TextField searchField;
	protected Button searchButton;
	protected CheckBox includePast;
	protected Button newOrder;
	protected Order list;

	public BusquedaViewDesign() {
		Design.read(this);
	}
}
