package uy.edu.ude.sipro.ui.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ElementoDetalleViewDesign extends VerticalLayout {
	protected Button btnVolver;
	protected Button btnGuardar;
	protected Button btnModificar;
	protected Button btnCancelar;
	protected TextField txtNombreElemento;
	protected RadioButtonGroup<java.lang.String> chEsCategoria;
	protected RadioButtonGroup<java.lang.String> chTipo;
	protected ComboBox<uy.edu.ude.sipro.valueObjects.ElementoVO> cmbElementoRelacion;
	protected Button btnAgregarRelacion;
	protected Button btnEliminarRelacion;
	protected Grid<uy.edu.ude.sipro.valueObjects.SubElementoVO> grdElementoProyecto;
	protected TextField txtSinonimo;
	protected Button btnAgregarSinonimo;
	protected Button btnEliminarSinonimo;
	protected Grid<uy.edu.ude.sipro.valueObjects.SinonimoVO> grdSinonimos;

	public ElementoDetalleViewDesign() {
		Design.read(this);
	}
}
