package uy.edu.ude.sipro.ui.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PerfilViewDesign extends VerticalLayout {
	protected Button btnGuardar;
	protected Button btnEditar;
	protected Button btnCancelar;
	protected TextField txtNombre;
	protected TextField txtApellido;
	protected TextField txtEmail;
	protected CheckBox chkContrasenias;
	protected CssLayout cssContasenias;
	protected PasswordField txtContraseniaActual;
	protected PasswordField txtContrasenia;
	protected PasswordField txtRepetirContasenia;

	public PerfilViewDesign() {
		Design.read(this);
	}
}
