package uy.edu.ude.sipro.ui.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProyectoListadoViewDesign extends VerticalLayout {
	protected Button btnAgregar;
	protected Button btnVerDetalles;
	protected Button btnProcesar;
	protected Button btnEliminar;
	protected Grid<uy.edu.ude.sipro.valueObjects.ProyectoVO> grdProyectos;

	public ProyectoListadoViewDesign() {
		Design.read(this);
	}
}
