package uy.edu.ude.sipro.ui.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReportesViewDesign extends VerticalLayout {
	protected CssLayout layoutFiltros;
	protected Button btnGenerarReporte;
	protected Button btnLimpiar;
	protected ComboBox<java.lang.String> cmbTutor;
	protected Grid<uy.edu.ude.sipro.valueObjects.DocenteVO> grdTutores;
	protected ComboBox<java.lang.String> cmbCorrectores;
	protected Grid<uy.edu.ude.sipro.valueObjects.DocenteVO> grdCorrectores;
	protected ComboBox<java.lang.String> cmbElemento;
	protected Grid<uy.edu.ude.sipro.valueObjects.DocenteVO> grdElemntos;

	public ReportesViewDesign() {
		Design.read(this);
	}
}
