package uy.edu.ude.sipro.ui.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReportesViewDesign extends VerticalLayout {
	protected TabSheet tab;
	protected CssLayout reporteListados;
	protected Button btnGenerarReporte;
	protected Button btnLimpiar;
	protected ComboBox<uy.edu.ude.sipro.valueObjects.DocenteVO> cmbTutor;
	protected ComboBox<uy.edu.ude.sipro.valueObjects.DocenteVO> cmbCorrector;
	protected ComboBox<uy.edu.ude.sipro.valueObjects.ElementoVO> cmbElementos;
	protected Button btnAgregarRelacion;
	protected Button btnEliminarRelacion;
	protected Grid<uy.edu.ude.sipro.valueObjects.ElementoVO> grdElementoProyecto;
	protected HorizontalLayout layoutAnios;
	protected HorizontalLayout layoutNotas;
	protected CssLayout reportesGrafica;
	protected Button btnGenerarReporteGeneral;
	protected Button btnLimpiarGeneral;
	protected ComboBox<java.lang.String> cmbElementoGeneral;

	public ReportesViewDesign() {
		Design.read(this);
	}
}
